// Generated by CoffeeScript 1.3.3
(function() {

  window.level = [
    {
      time: 0,
      type: 'boss',
      icon: 0,
      w: 124,
      h: 124
    }
  ];

  window.levell = [
    {
      time: 0,
      type: 'enemy',
      icon: 9,
      x: 100,
      w: 64,
      h: 64
    }, {
      time: 30,
      type: 'enemy'
    }, {
      time: 60,
      type: 'enemy',
      x: 500,
      hp: 10
    }, {
      time: 60,
      type: 'friend',
      x: 500
    }, {
      time: 180,
      type: 'enemy',
      icon: 0,
      w: 124,
      h: 124
    }
  ];

}).call(this);
