// Generated by CoffeeScript 1.3.3
(function() {

  window.level = [
    {
      time: 0,
      type: 'enemy',
      param: null
    }, {
      time: 30,
      type: 'enemy',
      param: null
    }, {
      time: 60,
      type: 'enemy',
      param: null
    }
  ];

}).call(this);
