// Generated by CoffeeScript 1.3.3
(function() {

  window.level = [
    {
      time: 240,
      type: 'enemy',
      x: 100
    }, {
      time: 90,
      type: 'enemy',
      x: 500
    }, {
      time: 90,
      type: 'enemy',
      x: 100,
      w: 48,
      h: 48,
      icon: 8,
      hp: 3
    }, {
      time: 30,
      type: 'enemy',
      x: 100
    }, {
      time: 90,
      type: 'enemy',
      x: 500,
      w: 48,
      h: 48,
      icon: 8,
      hp: 3
    }, {
      time: 30,
      type: 'enemy',
      x: 500
    }, {
      time: 30,
      type: 'friend'
    }, {
      time: 180,
      type: 'boss',
      icon: 0,
      w: 124,
      h: 124,
      hp: 10
    }
  ];

}).call(this);
