// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  enchant();

  window.onload = function() {
    var game;
    game = new Game(640, 480);
    game.preload('img/icon0.png', 'img/battery.gif');
    game.onload = function() {
      var Boss, Enemy, Friend, Ship, back, battery, blueBulletLayer, center, currentIndex, enemyLayer, friendLayer, lastAge, mainState, map, redBulletLayer, ship, shipLayer, start, volt;
      Ship = (function(_super) {

        __extends(Ship, _super);

        function Ship(url) {
          var _this = this;
          if (url == null) {
            url = twitter_info['profile_image_url'];
          }
          Ship.__super__.constructor.call(this, 32, 32);
          Surface.load(url).onload = function(e) {
            var icon;
            icon = new Surface(_this.width, _this.height);
            icon.draw(e.target, 0, 0, _this.width, _this.height);
            return _this.image = icon;
          };
          this.x = (game.width - this.width) / 2;
          this.y = game.height - this.height - 10;
        }

        Ship.prototype.onenterframe = function() {
          if (this.age % 10 === 0) {
            return this.shoot();
          }
        };

        Ship.prototype.shoot = function() {
          var bullet, voltNum;
          voltNum = parseInt(volt.text);
          if (voltNum <= 0) {
            return;
          }
          volt.text = '' + (voltNum - 1);
          battery.frame = voltNum / 1000 | 0;
          bullet = new Sprite(16, 16);
          bullet.image = game.assets['img/icon0.png'];
          bullet.frame = 48;
          bullet.x = this.x + (this.width - bullet.width) / 2;
          bullet.y = this.y;
          bullet.onenterframe = function() {
            var e, _i, _len, _ref;
            this.y -= 10;
            _ref = enemyLayer.childNodes;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              e = _ref[_i];
              if (this.intersect(e)) {
                this.parentNode.removeChild(this);
                e.damage();
                return;
              }
            }
            if (this.y < -this.height) {
              return this.parentNode.removeChild(this);
            }
          };
          return blueBulletLayer.addChild(bullet);
        };

        Ship.prototype.updateTarget = function(x, y) {
          var dist, from;
          from = {
            x: this.x + this.width / 2,
            y: this.y + this.height / 2
          };
          dist = Math.sqrt(Math.pow(x - from.x, 2) + Math.pow(y - from.y, 2));
          this.tl.clear();
          return this.tl.moveTo(x - this.width / 2, y - this.height / 2, dist / 10, enchant.Easing.SIN_EASEINOUT);
        };

        Ship.prototype.addFriend = function(friend) {
          friend.dy = this.height;
          if (shipLayer.childNodes.length === 1) {
            friend.dx = -friend.width;
          } else if (shipLayer.childNodes.length === 2) {
            friend.dx = this.width;
          }
          friendLayer.removeChild(friend);
          return shipLayer.addChild(friend);
        };

        Ship.prototype.damage = function() {
          var len;
          len = shipLayer.childNodes.length;
          if (len === 1) {
            return game.end();
          } else {
            return shipLayer.removeChild(shipLayer.childNodes[len - 1]);
          }
        };

        return Ship;

      })(Sprite);
      Friend = (function(_super) {

        __extends(Friend, _super);

        Friend.prototype.counter = 0;

        function Friend(param) {
          var _this = this;
          Friend.__super__.constructor.call(this, home_timeline[Friend.prototype.counter].user.profile_image_url);
          Friend.prototype.counter++;
          this.tl.rotateTo(360, 30).then(function() {
            return _this.rotation = 0;
          });
          this.tl.loop();
          this.x = param.x || (game.width / this.width) / 2;
          this.y = param.y || -this.height;
          this.help = new MutableText(this.x - 16, this.y - 16);
          this.help.text = 'HELP';
          friendLayer.addChild(this.help);
          this.onenterframe = this.initState;
        }

        Friend.prototype.initState = function() {
          this.y += 1;
          this.help.x = this.x - 16;
          this.help.y = this.y - 16;
          if (this.y > game.height) {
            this.help.parentNode.removeChild(this.help);
            return this.parentNode.removeChild(this);
          } else if (this.intersect(ship)) {
            this.tl.clear();
            this.rotation = 0;
            this.help.parentNode.removeChild(this.help);
            ship.addFriend(this);
            return this.onenterframe = this.joinState;
          }
        };

        Friend.prototype.joinState = function() {
          this.x = ship.x + this.dx;
          this.y = ship.y + this.dy;
          if (ship.age % 10 === 0) {
            return this.shoot();
          }
        };

        return Friend;

      })(Ship);
      Enemy = (function(_super) {

        __extends(Enemy, _super);

        function Enemy(param) {
          var url,
            _this = this;
          Enemy.__super__.constructor.call(this, param.w || 32, param.h || 32);
          url = daily_ranking.rankings[param.icon != null ? param.icon : 9].icon;
          Surface.load(url).onload = function(e) {
            var icon;
            icon = new Surface(_this.width, _this.height);
            icon.draw(e.target, 0, 0, _this.width, _this.height);
            return _this.image = icon;
          };
          this.x = param.x || (game.width - this.width) / 2;
          this.y = param.y || -this.height;
          this.hp = param.hp || 1;
        }

        Enemy.prototype.onenterframe = function() {
          this.y += 1;
          if (this.age % 5 === 0) {
            return this.shoot();
          }
        };

        Enemy.prototype.shoot = function() {
          var bullet;
          bullet = new Sprite(16, 16);
          bullet.image = game.assets['img/icon0.png'];
          bullet.frame = 60;
          bullet.x = this.x + (this.width - bullet.width) / 2;
          bullet.y = this.y + this.height;
          bullet.onenterframe = function() {
            var e, _i, _len, _ref;
            this.y += 10;
            _ref = shipLayer.childNodes;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              e = _ref[_i];
              if (this.intersect(e)) {
                this.parentNode.removeChild(this);
                ship.damage();
                return;
              }
            }
            if (this.y > game.height) {
              return this.parentNode.removeChild(this);
            }
          };
          return redBulletLayer.addChild(bullet);
        };

        Enemy.prototype.damage = function() {
          this.hp--;
          if (this.hp <= 0) {
            return this.parentNode.removeChild(this);
          }
        };

        return Enemy;

      })(Sprite);
      Boss = (function(_super) {

        __extends(Boss, _super);

        function Boss(param) {
          var _this = this;
          Boss.__super__.constructor.call(this, param);
          this.tl.moveTo(this.x, 10, 90).delay(30).then(function() {
            _this.center = _this.x + _this.width / 2;
            _this.age = 0;
            _this.damage = _this.bossDamage;
            return _this.onenterframe = _this.waveState;
          });
          this.damage = (function() {});
          this.onenterframe = (function() {});
        }

        Boss.prototype.waveState = function() {
          this.x = this.center + Math.sin(this.age * 2 * Math.PI / 180) * 320 - this.width / 2;
          if (this.age % 10 === 0) {
            return this.shoot();
          }
        };

        Boss.prototype.bossDamage = function() {
          this.hp--;
          if (this.hp <= 0) {
            return game.clear();
          }
        };

        return Boss;

      })(Enemy);
      shipLayer = new Group;
      friendLayer = new Group;
      enemyLayer = new Group;
      blueBulletLayer = new Group;
      redBulletLayer = new Group;
      back = new Sprite(game.width, game.height);
      ship = new Ship;
      shipLayer.addChild(ship);
      game.rootScene.addEventListener(Event.TOUCH_START, function(e) {
        return ship.updateTarget(e.x, e.y);
      });
      battery = new Sprite(48, 40);
      battery.image = game.assets['img/battery.gif'];
      battery.frame = 3;
      battery.x = 10;
      volt = new MutableText(battery.x, battery.y + battery.height);
      volt.text = '' + electric;
      start = new Sprite(236, 48);
      start.x = (game.width - start.width) / 2;
      start.y = (game.height - start.height) / 2;
      start.image = game.assets['img/start.png'];
      start.onenterframe = function() {
        if (this.age > 90) {
          return this.parentNode.removeChild(this);
        }
      };
      currentIndex = lastAge = 0;
      mainState = function() {
        var event, _results;
        _results = [];
        while (this.age >= lastAge + level[currentIndex].time) {
          event = level[currentIndex];
          if (event.type === 'enemy') {
            enemyLayer.addChild(new Enemy(event));
          } else if (event.type === 'friend') {
            friendLayer.addChild(new Friend(event));
          } else if (event.type === 'boss') {
            enemyLayer.addChild(new Boss(event));
          }
          currentIndex++;
          lastAge = this.age;
          if (currentIndex >= level.length) {
            game.rootScene.onenterframe = (function() {});
            break;
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };
      game.rootScene.onenterframe = mainState;
      game.rootScene.addChild(back);
      game.rootScene.addChild(shipLayer);
      game.rootScene.addChild(friendLayer);
      game.rootScene.addChild(enemyLayer);
      game.rootScene.addChild(blueBulletLayer);
      game.rootScene.addChild(redBulletLayer);
      game.rootScene.addChild(battery);
      game.rootScene.addChild(volt);
      game.rootScene.addChild(start);
      center = new google.maps.LatLng(start_lat, start_lng);
      map = new google.maps.Map(back._element, {
        zoom: 18,
        center: center,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        disableDefaultUI: true
      });
      return game.rootScene.addEventListener(Event.ENTER_FRAME, function() {
        center = new google.maps.LatLng(center.lat() + 0.000003, center.lng());
        return map.setCenter(center);
      });
    };
    game.start();
    return navigator.geolocation.getCurrentPosition(function(pos) {
      return $.post('./updatelatlng', {
        lat: pos.coords.latitude,
        lng: pos.coords.longitude
      });
    });
  };

}).call(this);
