// Generated by CoffeeScript 1.3.3
(function() {

  enchant();

  window.onload = function() {
    var game;
    game = new Game(640, 480);
    game.onload = function() {
      var back, bear, center, map;
      back = new Sprite(game.width, game.height);
      bear = new Sprite(32, 32);
      bear.image = Surface.load(twitter_info['profile_image_url']);
      game.rootScene.addEventListener(Event.TOUCH_START, function(e) {
        bear.x = e.x;
        return bear.y = e.y;
      });
      game.rootScene.addChild(back);
      game.rootScene.addChild(bear);
      center = new google.maps.LatLng(start_lat, start_lng);
      map = new google.maps.Map(back._element, {
        zoom: 18,
        center: center,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      });
      return game.rootScene.addEventListener(Event.ENTER_FRAME, function() {
        center = new google.maps.LatLng(center.lat() + 0.000003, center.lng());
        return map.setCenter(center);
      });
    };
    game.start();
    return navigator.geolocation.getCurrentPosition(function(pos) {
      return $.post('./updatelatlng', {
        lat: pos.coords.latitude,
        lng: pos.coords.longitude
      });
    });
  };

}).call(this);
